import { logout as logoutApi } from '@/api/login'
import { setCache, removeCache } from '@/utils/cache'

const state = reactive({
  token: '',
  name: '',
  avatar: '',
  roles: '',
  permissions: ''
} as UTSJSONObject)

const setToken = (token: string): void => {
  state.token = token
}

const setName = (name: string): void => {
  state.name = name
}

const setAvatar = (avatar: string): void => {
  state.avatar = avatar
}

const setRoles = (roles: string): void => {
  state.roles = roles
}

const setPermissions = (permissions: string): void => {
  state.permissions = permissions
}


// 退出系统
const logout = (): Promise<any | null> => {
  return new Promise<any | null>((resolve: (value: any | null) => void, reject: (error?: any) => void) => {
    logoutApi().then((): void => {
      setToken('')
      setRoles('')
      setPermissions('')
      removeCache('App-Token')
      resolve(null)
    }).catch((error?: any) => {
      reject(error)
    })
  })
}

export default {
  state,
  setToken,
  setName,
  setAvatar,
  setRoles,
  setPermissions,
  logout
} as UTSJSONObject
