import { login as loginApi, getUserInfo as getUserInfoApi, logout as logoutApi } from '@/api/login'
import cacheKey, { setCache, removeCache } from '@/utils/cache'

const state = reactive({
  theme: 'light',
  token: '',
  name: '',
  avatar: '',
  roles: [] as Array<string>,
  permissions: [] as Array<string>
} as UTSJSONObject)


const changeTheme = (): void => {
  state.theme = state.theme === 'light' ? 'dark' : 'light'
}

const setToken = (token: string): void => {
  state.token = token
}

const setName = (name: string): void => {
  state.name = name
}

const setAvatar = (avatar: string): void => {
  state.avatar = avatar
}

const setRoles = (roles: Array<string>): void => {
  state.roles = roles
}

const setPermissions = (permissions: Array<string>): void => {
  state.permissions = permissions
}


// 登录
const login = (userInfo: UTSJSONObject): Promise<any | null> => {
  const username: string = userInfo['username'] as string
  const password: string = userInfo['password'] as string
  const code: string = userInfo['code'] as string
  const uuid: string = userInfo['uuid'] as string
  return new Promise<any | null>((resolve: (value: any | null) => void, reject: (error?: any) => void) => {
    loginApi(username, password, code, uuid).then((response: any | null): void => {
      const res: UTSJSONObject = response as UTSJSONObject
      setCache(cacheKey.AppToken as string, res['access_token'] as string)
      setToken(res['access_token'] as string)
      resolve(null)
    }).catch((error?: any) => {
      reject(error)
    })
  })
}

// 获取登录用户信息
const getUserInfo = (): Promise<any | null> => {
  return new Promise<any | null>((resolve: (value: any | null) => void, reject: (error?: any) => void) => {
    getUserInfoApi().then((response: any | null): void => {
      const res: UTSJSONObject = response as UTSJSONObject
      const user: UTSJSONObject = res['user'] as UTSJSONObject
      setRoles(res['roles'] as Array<string>)
      setPermissions(res['permissions'] as Array<string>)
      setName(user['nickName'] as string)
      setAvatar(user['avatar'] != null ? user['avatar'] as string : '/static/images/avatar.jpg')
      resolve(null)
    }).catch((error?: any) => {
      reject(error)
    })
  })
}

// 退出系统
const logout = (): Promise<any | null> => {
  return new Promise<any | null>((resolve: (value: any | null) => void, reject: (error?: any) => void) => {
    logoutApi().then((): void => {
      setToken('')
      setRoles([])
      setPermissions([])
      removeCache(cacheKey.AppToken as string)
      resolve(null)
    }).catch((error?: any) => {
      reject(error)
    })
  })
}

export default {
  state,
  changeTheme,
  setToken,
  setName,
  setAvatar,
  setRoles,
  setPermissions,
  login,
  getUserInfo,
  logout
} as UTSJSONObject
