import request, { IRequest, IHeaders } from '@/utils/request'

/**
 * 获取验证码
 */
export function getCaptcha(): Promise<any | null> {
  return request({
    url: '/auth/captcha',
    headers: {
      isToken: false
    } as IHeaders,
    method: 'GET',
    timeout: 20000
  } as IRequest)
}

/**
 * 账密登录
 * @param {string} username
 * @param {string} password
 * @param {string} code
 * @param {string} uuid
 * @param {string} isSoterAuth
 */
export function login(username: string, password: string, code: string, uuid: string, isSoterAuth: boolean): Promise<any | null> {
  const data = {
    username,
    password,
    code,
    uuid,
    isSoterAuth
  } as UTSJSONObject
  return request({
    url: '/auth/app-login',
    headers: {
      isToken: false
    } as IHeaders,
    method: 'POST',
    data: data
  } as IRequest)
}

/**
 * 扫码登录
 * @param {string} qrCode
 * @param {string} type
 */
export function scanLogin(qrCode: string, type: string): Promise<any | null> {
  return request({
    url: '/auth/app-scan',
    method: 'GET',
    params: { qrCode, type }
  } as IRequest)
}

/**
 * 获取用户详细信息
 */
export function getUserInfo(): Promise<any | null> {
  return request({
    url: '/auth/getUserInfo',
    method: 'GET'
  } as IRequest)
}

/**
 * 退出方法
 */
export function logout(): Promise<any | null> {
  return request({
    url: '/auth/logout',
    method: 'DELETE'
  } as IRequest)
}
