import request, { IRequest, IHeaders } from '@/utils/request'

/**
 * 登录方法
 * @param {string} username
 * @param {string} password
 * @param {string} code
 * @param {string} uuid
 */
export function login(username: string, password: string, code: string, uuid: string): Promise<any> {
  const data = {
    username,
    password,
    code,
    uuid
  } as UTSJSONObject
  return request({
    url: '/login',
    headers: {
      isToken: false
    } as IHeaders,
    method: 'POST',
    data: data
  } as IRequest)
}

/**
 * 获取用户详细信息
 */
export function getInfo(): Promise<any> {
  return request({
    url: '/getInfo',
    method: 'GET'
  } as IRequest)
}

/**
 * 退出方法
 */
export function logout(): Promise<any> {
  return request({
    url: '/logout',
    method: 'POST'
  } as IRequest)
}

/**
 * 获取验证码
 */
export function getCaptcha(): Promise<any> {
  return request({
    url: '/captcha',
    headers: {
      isToken: false
    } as IHeaders,
    method: 'GET',
    timeout: 20000
  } as IRequest)
}
